### PR TITLE
Update acf pro example link

### PR DESCRIPTION
**Pull request by vinkla**
There is a new link available when you download ACF Pro from the website.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Do they have a new API?

**Comment by szepeviktor** [comment]
Could you get an older version of the plugin from this API?

**Comment by szepeviktor** [comment]
> Could you get an older version of the plugin from this API?

Or were different versions already available with `/index.php`? (I do not remember)

**Comment by vinkla** [comment]
> Do they have a new API?

I've been using this URL for some time.

> > Could you get an older version of the plugin from this API?
>
> Or were different versions already available with /index.php? (I do not remember)

It seems it is only possible to download version 5.0+ from both links.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by vinkla** [comment]
Closing this since [ACF has released Composer support](https://www.advancedcustomfields.com/resources/installing-acf-pro-with-composer/).

**Comment by szepeviktor** [comment]
> Closing this since ACF has released Composer support

I will still use `private-composer-installer` as **it works*. I do not know anything about their repository.

**Pull request closed without merging**
