### PR TITLE
Re-work .env file loading

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This PR implements robust support for phpdotenv v4 and v5, and also support for searching for .env files in multiple directories (by default, recursing upwards).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB I've not tested this (yet). :P

**Comment by GrahamCampbell** [comment]
Still not right. But it's very late now... will finish this off tomorrow (later today :troll:).

**Comment by szepeviktor** [comment]
Isn't this worked on in that PR? https://github.com/ffraenz/private-composer-installer/pull/25/files#diff-9566a978dedbda24bbf9a2217952f596851a1c1b892263e7dbc172dfe0175a62R54

**Comment by ffraenz** [comment]
Good stuff! Thank you! I'd suggest renaming `AbstractLoader` and `LoaderFactory` to `AbstractDotenvLoader` and `DotenvLoaderFactory`. More ways of obtaining environment variables, especially time or session based tokens, may be introduced in the future. `LoaderInterface` may be acting as the common denominator. I'll merge the PR later today and fix the testing issues.

**Comment by ffraenz** [comment]
To solve #26 in one go, we could take advantage of phpdotenv's multiple path and file name support with short circuit enabled to traverse the directory levels above the working directory in order to search for a `.env` file.

I'd suggest to extend the abstract loader to support multiple paths and names and to extend the factory by:

```php
if ($paths === null) {
    $current = getcwd();
    $paths = [$current];
    while (!in_array($current, ['.', '/', '\\'])) {
      $current = dirname($current);
      $paths[] = $current;
    }
}
```

**Comment by GrahamCampbell** [comment]
@szepeviktor This PR targets that PR's source branch.

**Comment by GrahamCampbell** [comment]
@ffraenz Alright, fixed up this so that it actually works now. ;)

**Review by ffraenz — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
