### PR TITLE
Add acf_pro_license option to README

### PR DESCRIPTION
**Pull request by szepeviktor**
plus syntax highlight
plus more visible double-quotes: `"`

### CODE REVIEW

**Comment by szepeviktor** [comment]
Because I always forget that option's name!

**Comment by szepeviktor** [comment]
@jarednova See how @coveralls is growing!

😿

**Comment by szepeviktor** [comment]
_Houston, we've had a problem_
https://www.youtube.com/watch?v=MdvoA-sjs0A

That option contains a BASE64 encoded serialized mess.
In shell:

```bash
echo $ACF_OPTION | php -r 'echo unserialize(base64_decode(fgets(STDIN)))["key"]; echo PHP_EOL;'
```

**Comment by jarednova** [comment]
@szepeviktor yeah, saw you're sternly worded tweet. seemed to get their attention!

**Comment by ffraenz** [comment]
Hi @szepeviktor! I'd like to send people in the right direction when they are looking for an ACF license key. Because this project is not ACF exclusive I'd like to keep it short, though. Maybe we add a repo wiki page with usage examples where we can elaborate (e.g. including the shell snippet you mentioned) and link to it in the README?

**Comment by szepeviktor** [comment]
Okay.

**Comment by szepeviktor** [comment]
Ooops, there is no Wiki.

**Pull request closed without merging**
